/**
 * REA — იტალიის პროვინციების კოდები (sigla).
 * KYB · Azienda გვერდი: REA ველის ფორმატია "{code}-{digits}", მაგ. "MI-987654".
 * ეს სია დეველოპერისგან მოწოდებული (portal-ის მხარდაჭერილი კოდები).
 */
export type ReaProvince = { code: string; name: string };

export const REA_PROVINCES: ReaProvince[] = [
  { code: 'AG', name: 'AGRIGENTO' },
  { code: 'AL', name: 'ALESSANDRIA' },
  { code: 'AN', name: 'ANCONA' },
  { code: 'AO', name: 'AOSTA' },
  { code: 'AP', name: 'ASCOLI PICENO' },
  { code: 'AQ', name: "L'AQUILA" },
  { code: 'AR', name: 'AREZZO' },
  { code: 'AT', name: 'ASTI' },
  { code: 'AV', name: 'AVELLINO' },
  { code: 'BA', name: 'BARI' },
  { code: 'BG', name: 'BERGAMO' },
  { code: 'BI', name: 'BIELLA' },
  { code: 'BL', name: 'BELLUNO' },
  { code: 'BN', name: 'BENEVENTO' },
  { code: 'BO', name: 'BOLOGNA' },
  { code: 'BR', name: 'BRINDISI' },
  { code: 'BS', name: 'BRESCIA' },
  { code: 'BT', name: 'BARLETTA-ANDRIA-TRANI' },
  { code: 'BZ', name: 'BOLZANO' },
  { code: 'CA', name: 'CAGLIARI' },
  { code: 'CB', name: 'CAMPOBASSO' },
  { code: 'CE', name: 'CASERTA' },
  { code: 'CH', name: 'CHIETI' },
  { code: 'CI', name: 'CARBONIA-IGLESIAS' },
  { code: 'CL', name: 'CALTANISSETTA' },
  { code: 'CN', name: 'CUNEO' },
  { code: 'CO', name: 'COMO' },
  { code: 'CR', name: 'CREMONA' },
  { code: 'CS', name: 'COSENZA' },
  { code: 'CT', name: 'CATANIA' },
  { code: 'CZ', name: 'CATANZARO' },
  { code: 'EN', name: 'ENNA' },
  { code: 'FC', name: "FORLI'-CESENA" },
  { code: 'FE', name: 'FERRARA' },
  { code: 'FG', name: 'FOGGIA' },
  { code: 'FI', name: 'FIRENZE' },
  { code: 'FM', name: 'FERMO' },
  { code: 'FO', name: "FORLI'" },
  { code: 'FR', name: 'FROSINONE' },
  { code: 'FU', name: 'FIUME' },
  { code: 'GE', name: 'GENOVA' },
  { code: 'GO', name: 'GORIZIA' },
  { code: 'GR', name: 'GROSSETO' },
  { code: 'IM', name: 'IMPERIA' },
  { code: 'IS', name: 'ISERNIA' },
  { code: 'KR', name: 'CROTONE' },
  { code: 'LC', name: 'LECCO' },
  { code: 'LE', name: 'LECCE' },
  { code: 'LI', name: 'LIVORNO' },
  { code: 'LO', name: 'LODI' },
  { code: 'LT', name: 'LATINA' },
  { code: 'LU', name: 'LUCCA' },
  { code: 'MB', name: 'MONZA E BRIANZA' },
  { code: 'MC', name: 'MACERATA' },
  { code: 'ME', name: 'MESSINA' },
  { code: 'MI', name: 'MILANO' },
  { code: 'MN', name: 'MANTOVA' },
  { code: 'MO', name: 'MODENA' },
  { code: 'MS', name: 'MASSA-CARRARA' },
  { code: 'MT', name: 'MATERA' },
  { code: 'NA', name: 'NAPOLI' },
  { code: 'NO', name: 'NOVARA' },
  { code: 'NU', name: 'NUORO' },
  { code: 'OG', name: 'OGLIASTRA' },
  { code: 'OR', name: 'ORISTANO' },
  { code: 'OT', name: 'OLBIA-TEMPIO' },
  { code: 'PA', name: 'PALERMO' },
  { code: 'PC', name: 'PIACENZA' },
  { code: 'PD', name: 'PADOVA' },
  { code: 'PE', name: 'PESCARA' },
  { code: 'PG', name: 'PERUGIA' },
  { code: 'PI', name: 'PISA' },
  { code: 'PL', name: 'POLA' },
  { code: 'PN', name: 'PORDENONE' },
  { code: 'PO', name: 'PRATO' },
  { code: 'PR', name: 'PARMA' },
  { code: 'PS', name: 'PESARO' },
  { code: 'PT', name: 'PISTOIA' },
  { code: 'PU', name: 'PESARO-URBINO' },
  { code: 'PU', name: 'PESARO E URBINO' },
  { code: 'PV', name: 'PAVIA' },
  { code: 'PZ', name: 'POTENZA' },
  { code: 'RA', name: 'RAVENNA' },
  { code: 'RC', name: 'REGGIO DI CALABRIA' },
  { code: 'RC', name: 'REGGIO CALABRIA' },
  { code: 'RE', name: "REGGIO NELL'EMILIA" },
  { code: 'RG', name: 'RAGUSA' },
  { code: 'RI', name: 'RIETI' },
  { code: 'RM', name: 'ROMA' },
  { code: 'RN', name: 'RIMINI' },
  { code: 'RO', name: 'ROVIGO' },
  { code: 'SA', name: 'SALERNO' },
  { code: 'SI', name: 'SIENA' },
  { code: 'SO', name: 'SONDRIO' },
  { code: 'SP', name: 'LA SPEZIA' },
  { code: 'SR', name: 'SIRACUSA' },
  { code: 'SS', name: 'SASSARI' },
  { code: 'SU', name: 'SUD SARDEGNA' },
  { code: 'SV', name: 'SAVONA' },
  { code: 'TA', name: 'TARANTO' },
  { code: 'TE', name: 'TERAMO' },
  { code: 'TN', name: 'TRENTO' },
  { code: 'TO', name: 'TORINO' },
  { code: 'TP', name: 'TRAPANI' },
  { code: 'TR', name: 'TERNI' },
  { code: 'TS', name: 'TRIESTE' },
  { code: 'TV', name: 'TREVISO' },
  { code: 'UD', name: 'UDINE' },
  { code: 'VA', name: 'VARESE' },
  { code: 'VB', name: 'VERBANIA' },
  { code: 'VC', name: 'VERCELLI' },
  { code: 'VE', name: 'VENEZIA' },
  { code: 'VI', name: 'VICENZA' },
  { code: 'VR', name: 'VERONA' },
  { code: 'VS', name: 'MEDIO CAMPIDANO' },
  { code: 'VT', name: 'VITERBO' },
  { code: 'VV', name: 'VIBO VALENTIA' },
  { code: 'ZA', name: 'ZARA' },
];